### ISSUE TITLE
Using imba with Foundation 5 css framework custom attribute containing dash "-" doesn't compile.

### ISSUE THREAD

**Issue by mxvanzant** [somebee/imba#25]
Hi. I'm attempting to use imba with Foundation 5 CSS framework. For example, when creating a top menu  bar (nav bar), imba compiler gives error on the data-topbar custom attribute:
```imba
def top_bar name
  <div.fixed>
    <nav.top-bar data-topbar role='navigation'>
      <ul.title-area>
        <li.name>
          <h1>
            <a href='#'> name
```
I get:
```
[0:1] Parse error on line 3: Unexpected 'CALL_START'
```
Any ideas? Thanks! BTW, really liking imba!!!

**Comment by judofyr** [comment]
The easiest way is to provide a custom setter:

```imba
tag nav
    def topbar= enabled
        setAttribute('data-topbar', enabled)
        self

<nav topbar=true>
```

Remember that the tag-syntax er merely a syntax sugar for calling setters. As long as you remember to `return self` in the setters, they can be as complex as you'd like.

**Comment by judofyr** [comment]
But yeah, the "proper" way would be to use:

```imba
tag nav
    prop data-topbar dom: true
```

But at the moment Imba will set the attribute "dataTopbar", not "data-topbar".

**Comment by mxvanzant** [comment]
Cool thanks!

**Comment by somebee** [comment]
Thanks for submitting the issue @mxvanzant.
 I have now (pushed)[https://github.com/somebee/imba/commit/02a38247cae0d1ecace828dda0b2c598c16de316] support for data-attributes. As @judofyr mentioed, the tag-syntax is simply compiling to a chain of setters. So you cannot do `<div custom=1>` if you haven't defined a `setCustom` on the div tag. Data-attributes are special though (they are always allowed). Not sure if it is the best solution, but I've now implemented them so that `data-mykey=1` compiles to `.dataset('mykey',1)`. Please let me know if it works for you. I will push a new version to npm later today.

**Comment by mxvanzant** [comment]
Thanks. I will try it out and let you know.

**Comment by mxvanzant** [comment]
Works. Thanks!
