### ISSUE TITLE
Parse error: Unexpected 'TERMINATOR'

### ISSUE THREAD

**Issue by sleewoo** [somebee/imba#34]
stuff like this wont compile:

```imba
if var album = @albums.filter( do |a| a:id == parseInt(self:params:album) )[0]
```

Even this minimal case fails:
```imba
if filter(do yes)[0]
    yes
```

**Comment by somebee** [comment]
This is now fixed, but there is still some related unexpected behaviour. This does not compile:
```imba
if filter(do something).save
	yes
```
The fix for this is slightly more intrusive as it requires restructuring the rewriter. The tokenizer/rewriter is a huge mess compared to the rest of the compiler, and I'm pondering a complete rewrite of them. Until then , the above rare issue can be worked around by adding explicit parens around save:
```imba
if filter(do something).save()
	yes
```

**Comment by sleewoo** [comment]
thanks
